//Modelos de la base de datos. Diseñar el esquema de los datos. 
const mongoose = require('mongoose'); //Vamos a requerir mongoose y se guarda en una constante, pero no para conectarnos, sino para modelar los datos
const { Schema } = mongoose; //Solamente requiero una parte de mongoose, requiero solamente el schema (Esquema) Para definir el esquema de los datos. Propiedades de un contratista etc

const ContractorsSchema = new Schema({ //constante de las tareas
    cedula: { type: String, required: true},
    nombre: { type: String, required: true},
    supervisor: { type: String, required: true},
    direccion: { type: String, required: true},
    telefono: { type: String, required: true},
    correo: { type: String, required: true},
    ciudad: { type: String, required: true},
    objeto: { type: String, required: true},
    rpc: { type: String, required: true},
    cdp: { type: String, required: true},
    numero_de_Contrato: { type: String, required: true},
    fecha_de_Contrato: { type: String, required: true},
    valor_Inicial_Contrato: { type: String, required: true},
    valor_Cuota: { type: String, required: true},
    valor_en_letras: { type: String, required: true},
    obligación_1: { type: String, required: true},
    obligación_2: { type: String, required: true},
    obligación_3: { type: String, required: true},
    obligación_4: { type: String, required: true},
    obligación_5: { type: String, required: true},
    obligación_6: { type: String, required: true},
    obligación_7: { type: String, required: true},
    obligación_8: { type: String, required: true},
    obligación_9: { type: String, required: true},
    obligación_10: { type: String, required: true},
    año_de_Transaccion: { type: String, required: true},
    apropiación_Presupuestal: { type: String, required: true},
    proyecto: { type: String, required: true},
    linea_Estrategica: { type: String, required: true},
    enfasis_de_Gobierno: { type: String, required: true},
    sectores_Relacionados: { type: String, required: true},
    linea_de_Accion: { type: String, required: true},
    programa: { type: String, required: true},
    meta_de_Resultado: { type: String, required: true},
    subprograma: { type: String, required: true},
    meta_de_Producto: { type: String, required: true},
    valor_Adicional: { type: String, required: true},
    valor_Total: { type: String, required: true},
    cuota: { type: String, required: true}, 
    mes_de_Cuota: { type: String, required: true},
    no_Equivalente: { type: String, required: true},
    no_Planilla: { type: String, required: true},
    mes_de_Planilla: { type: String, required: true},
    dia_de_la_Transaccion: { type: String, required: true},
    mes_de_la_Transaccion: { type: String, required: true},
    numero_de_Pago: { type: String, required: true},
    porcentaje: { type: String, required: true},
    valor_Pagado: { type: String, required: true}, 
    valor_Causado_no_Pagado: { type: String, required: true},
    valor_Total_Ejecutado: { type: String, required: true},
    valor_Saldo_por_Ejecutar: { type: String, required: true},
    dia_del_Proximo_Informe: { type: String, required: true},
    mes_del_Proximo_Informe: { type: String, required: true},
    tipo_de_Cuenta: { type: String, required: true},
    no_Cuenta: { type: String, required: true}, 
    banco: { type: String, required: true}
});

module.exports = mongoose.model('Contractors', ContractorsSchema); //Mongosse tiene un metodo llamado model el cual le damos el nombre del modelo y como estructura tendra el esquema definido arriba